import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>Cho-HELPDESK</h1>
          <Link href="/">Dashbord</Link>
          <Link href="/tickets">Tickets</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
